music.setVolume(50)
basic.forever(function () {
    while (mbit_小車類.Avoid_Sensor(mbit_小車類.enAvoidState.OBSTACLE)) {
        mbit_小車類.CarCtrlSpeed(mbit_小車類.CarState.Car_Run, 0)
    }
    mbit_小車類.CarCtrlSpeed2(mbit_小車類.CarState.Car_Run, 40, 42)
    basic.pause(1000)
    mbit_小車類.CarCtrlSpeed2(mbit_小車類.CarState.Car_Run, 0, 0)
    basic.showString("Hamburger")
    mbit_小車類.CarCtrlSpeed2(mbit_小車類.CarState.Car_Run, 40, 42)
    basic.pause(1000)
    mbit_小車類.CarCtrlSpeed2(mbit_小車類.CarState.Car_Run, 0, 0)
    basic.showString("Pearl Milk Tea")
    mbit_小車類.CarCtrlSpeed2(mbit_小車類.CarState.Car_Run, 40, 42)
    basic.pause(1000)
    mbit_小車類.CarCtrlSpeed2(mbit_小車類.CarState.Car_Run, 0, 0)
    basic.showString("Takoyaki")
    mbit_小車類.CarCtrlSpeed2(mbit_小車類.CarState.Car_Run, 0, 70)
    basic.pause(500)
    mbit_小車類.CarCtrlSpeed2(mbit_小車類.CarState.Car_Run, 40, 42)
    basic.pause(500)
    mbit_小車類.CarCtrlSpeed2(mbit_小車類.CarState.Car_Run, 0, 0)
    basic.showString("Russian Shashlik")
    mbit_小車類.CarCtrlSpeed2(mbit_小車類.CarState.Car_Run, 40, 42)
    basic.pause(500)
    mbit_小車類.CarCtrlSpeed2(mbit_小車類.CarState.Car_Run, 0, 0)
    basic.showString("Avocado Toast")
    mbit_小車類.CarCtrlSpeed2(mbit_小車類.CarState.Car_Run, 40, 42)
    basic.pause(500)
    mbit_小車類.CarCtrlSpeed2(mbit_小車類.CarState.Car_Run, 0, 0)
    basic.showString("Fish and Chips")
    mbit_小車類.CarCtrlSpeed2(mbit_小車類.CarState.Car_Run, 0, 70)
    basic.pause(500)
    mbit_小車類.CarCtrlSpeed2(mbit_小車類.CarState.Car_Run, 40, 42)
    basic.pause(1000)
    mbit_小車類.CarCtrlSpeed2(mbit_小車類.CarState.Car_Run, 0, 0)
    basic.showString("Royal Pancake")
    mbit_小車類.CarCtrlSpeed2(mbit_小車類.CarState.Car_Run, 40, 42)
    basic.pause(1000)
    mbit_小車類.CarCtrlSpeed2(mbit_小車類.CarState.Car_Run, 0, 0)
    basic.showString("Spicy Rice Cake")
    mbit_小車類.CarCtrlSpeed2(mbit_小車類.CarState.Car_Run, 40, 42)
    basic.pause(1000)
    mbit_小車類.CarCtrlSpeed2(mbit_小車類.CarState.Car_Run, 0, 0)
    basic.showString("Taco")
    mbit_小車類.CarCtrlSpeed2(mbit_小車類.CarState.Car_Run, 0, 70)
    basic.pause(500)
    mbit_小車類.CarCtrlSpeed2(mbit_小車類.CarState.Car_Run, 40, 42)
    basic.pause(500)
    mbit_小車類.CarCtrlSpeed2(mbit_小車類.CarState.Car_Run, 0, 0)
    basic.showString("Bouillabaisse")
    mbit_小車類.CarCtrlSpeed2(mbit_小車類.CarState.Car_Run, 40, 42)
    basic.pause(500)
    mbit_小車類.CarCtrlSpeed2(mbit_小車類.CarState.Car_Run, 0, 0)
    basic.showString("Cheese fondue")
    mbit_小車類.CarCtrlSpeed2(mbit_小車類.CarState.Car_Run, 39, 42)
    basic.pause(500)
    mbit_小車類.CarCtrlSpeed2(mbit_小車類.CarState.Car_Run, 0, 0)
})
